// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu_EWRzSMTa-KpfS9c41UT2U3eIGKXbo0',
    appId: '1:177037378990:web:6dbe7f0655d486d2a0743f',
    messagingSenderId: '177037378990',
    projectId: 'awesomexpensemanager',
    authDomain: 'awesomexpensemanager.firebaseapp.com',
    storageBucket: 'awesomexpensemanager.firebasestorage.app',
    measurementId: 'G-GZT73EMXR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZ0IhC61uFNaV7BK1oI8c8flZ4Tipoo4',
    appId: '1:177037378990:android:48d63716918497cca0743f',
    messagingSenderId: '177037378990',
    projectId: 'awesomexpensemanager',
    storageBucket: 'awesomexpensemanager.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu_EWRzSMTa-KpfS9c41UT2U3eIGKXbo0',
    appId: '1:177037378990:web:3fa5540cbfa4a361a0743f',
    messagingSenderId: '177037378990',
    projectId: 'awesomexpensemanager',
    authDomain: 'awesomexpensemanager.firebaseapp.com',
    storageBucket: 'awesomexpensemanager.firebasestorage.app',
    measurementId: 'G-1W13K9HK1C',
  );
}
